export interface StudyResource {
  id: string;
  title: string;
  channelOrAuthor?: string;
  description?: string;
  category: string;
  categoryLabel: string;
  url?: string;
  iconType?: string;
}

export interface StudyCategory {
  id: string;
  title: string;
  shortDescription: string;
  iconName: string;
  gradient: string;
  accentHex: string;
  borderDark: string;
  borderLight: string;
  bgDark: string;
  bgLight: string;
}

export const STUDY_CATEGORIES: StudyCategory[] = [
  {
    id: 'c-programming',
    title: 'C Programming',
    shortDescription: 'Core fundamentals, pointers & systems foundations',
    iconName: 'Terminal',
    gradient: 'from-blue-600 via-indigo-600 to-cyan-500',
    accentHex: '#3b82f6',
    borderDark: 'rgba(59, 130, 246, 0.3)',
    borderLight: 'rgba(59, 130, 246, 0.25)',
    bgDark: 'rgba(59, 130, 246, 0.15)',
    bgLight: 'rgba(59, 130, 246, 0.08)',
  },
  {
    id: 'cpp-programming',
    title: 'C++ Programming',
    shortDescription: 'Object orientation, STL & high-performance computing',
    iconName: 'Code2',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-600',
    accentHex: '#06b6d4',
    borderDark: 'rgba(6, 182, 212, 0.3)',
    borderLight: 'rgba(6, 182, 212, 0.25)',
    bgDark: 'rgba(6, 182, 212, 0.15)',
    bgLight: 'rgba(6, 182, 212, 0.08)',
  },
  {
    id: 'python',
    title: 'Python',
    shortDescription: 'Scripting, modern applications & automated workflows',
    iconName: 'Binary',
    gradient: 'from-amber-500 via-orange-500 to-yellow-500',
    accentHex: '#f59e0b',
    borderDark: 'rgba(245, 158, 11, 0.3)',
    borderLight: 'rgba(245, 158, 11, 0.25)',
    bgDark: 'rgba(245, 158, 11, 0.15)',
    bgLight: 'rgba(245, 158, 11, 0.08)',
  },
  {
    id: 'java',
    title: 'Java',
    shortDescription: 'Enterprise architecture, JVM & multi-threaded systems',
    iconName: 'Coffee',
    gradient: 'from-red-500 via-rose-500 to-orange-600',
    accentHex: '#ef4444',
    borderDark: 'rgba(239, 68, 68, 0.3)',
    borderLight: 'rgba(239, 68, 68, 0.25)',
    bgDark: 'rgba(239, 68, 68, 0.15)',
    bgLight: 'rgba(239, 68, 68, 0.08)',
  },
  {
    id: 'dsa',
    title: 'Data Structures & Algorithms',
    shortDescription: 'Problem solving, trees, graphs, sorting & recursion',
    iconName: 'Network',
    gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
    accentHex: '#10b981',
    borderDark: 'rgba(16, 185, 129, 0.3)',
    borderLight: 'rgba(16, 185, 129, 0.25)',
    bgDark: 'rgba(16, 185, 129, 0.15)',
    bgLight: 'rgba(16, 185, 129, 0.08)',
  },
  {
    id: 'oops',
    title: 'Object-Oriented Programming',
    shortDescription: 'Encapsulation, inheritance, polymorphism & design patterns',
    iconName: 'Boxes',
    gradient: 'from-purple-500 via-violet-500 to-indigo-600',
    accentHex: '#a855f7',
    borderDark: 'rgba(168, 85, 247, 0.3)',
    borderLight: 'rgba(168, 85, 247, 0.25)',
    bgDark: 'rgba(168, 85, 247, 0.15)',
    bgLight: 'rgba(168, 85, 247, 0.08)',
  },
  {
    id: 'dbms',
    title: 'DBMS',
    shortDescription: 'Relational databases, SQL, ACID properties & indexing',
    iconName: 'Database',
    gradient: 'from-sky-500 via-blue-600 to-indigo-700',
    accentHex: '#0284c7',
    borderDark: 'rgba(2, 132, 199, 0.3)',
    borderLight: 'rgba(2, 132, 199, 0.25)',
    bgDark: 'rgba(2, 132, 199, 0.15)',
    bgLight: 'rgba(2, 132, 199, 0.08)',
  },
  {
    id: 'operating-systems',
    title: 'Operating Systems',
    shortDescription: 'Processes, concurrency, CPU scheduling & memory paging',
    iconName: 'Cpu',
    gradient: 'from-violet-600 via-purple-600 to-fuchsia-600',
    accentHex: '#8b5cf6',
    borderDark: 'rgba(139, 92, 246, 0.3)',
    borderLight: 'rgba(139, 92, 246, 0.25)',
    bgDark: 'rgba(139, 92, 246, 0.15)',
    bgLight: 'rgba(139, 92, 246, 0.08)',
  },
  {
    id: 'computer-networks',
    title: 'Computer Networks',
    shortDescription: 'OSI model, TCP/IP, subnetting, routing & socket protocols',
    iconName: 'Radio',
    gradient: 'from-teal-500 via-emerald-600 to-cyan-600',
    accentHex: '#14b8a6',
    borderDark: 'rgba(20, 184, 166, 0.3)',
    borderLight: 'rgba(20, 184, 166, 0.25)',
    bgDark: 'rgba(20, 184, 166, 0.15)',
    bgLight: 'rgba(20, 184, 166, 0.08)',
  },
  {
    id: 'coa',
    title: 'COA',
    shortDescription: 'Computer Organization & Architecture, pipelining, cache',
    iconName: 'Microchip',
    gradient: 'from-slate-600 via-gray-700 to-zinc-800',
    accentHex: '#71717a',
    borderDark: 'rgba(113, 113, 122, 0.3)',
    borderLight: 'rgba(113, 113, 122, 0.25)',
    bgDark: 'rgba(113, 113, 122, 0.15)',
    bgLight: 'rgba(113, 113, 122, 0.08)',
  },
  {
    id: 'toc-automata',
    title: 'TOC / Automata',
    shortDescription: 'Finite automata, regular grammars, PDA & Turing machines',
    iconName: 'Workflow',
    gradient: 'from-indigo-600 via-blue-600 to-teal-500',
    accentHex: '#4f46e5',
    borderDark: 'rgba(79, 70, 229, 0.3)',
    borderLight: 'rgba(79, 70, 229, 0.25)',
    bgDark: 'rgba(79, 70, 229, 0.15)',
    bgLight: 'rgba(79, 70, 229, 0.08)',
  },
  {
    id: 'compiler-design',
    title: 'Compiler Design',
    shortDescription: 'Lexical analysis, parsing, semantic checks & code generation',
    iconName: 'FileCode',
    gradient: 'from-fuchsia-600 via-pink-600 to-rose-600',
    accentHex: '#d946ef',
    borderDark: 'rgba(217, 70, 239, 0.3)',
    borderLight: 'rgba(217, 70, 239, 0.25)',
    bgDark: 'rgba(217, 70, 239, 0.15)',
    bgLight: 'rgba(217, 70, 239, 0.08)',
  },
  {
    id: 'web-development',
    title: 'Web Development',
    shortDescription: 'Frontend, backend, APIs, modern web frameworks & UX',
    iconName: 'Globe',
    gradient: 'from-emerald-500 via-cyan-500 to-blue-600',
    accentHex: '#10b981',
    borderDark: 'rgba(16, 185, 129, 0.3)',
    borderLight: 'rgba(16, 185, 129, 0.25)',
    bgDark: 'rgba(16, 185, 129, 0.15)',
    bgLight: 'rgba(16, 185, 129, 0.08)',
  },
  {
    id: 'software-engineering',
    title: 'Software Engineering',
    shortDescription: 'SDLC, Agile methodology, testing, QA & project architecture',
    iconName: 'Layers',
    gradient: 'from-blue-600 via-indigo-600 to-purple-600',
    accentHex: '#2563eb',
    borderDark: 'rgba(37, 99, 235, 0.3)',
    borderLight: 'rgba(37, 99, 235, 0.25)',
    bgDark: 'rgba(37, 99, 235, 0.15)',
    bgLight: 'rgba(37, 99, 235, 0.08)',
  },
  {
    id: 'git-github',
    title: 'Git & GitHub',
    shortDescription: 'Version control, branching, PRs, merge workflows & CI/CD',
    iconName: 'GitBranch',
    gradient: 'from-orange-600 via-red-600 to-pink-600',
    accentHex: '#ea580c',
    borderDark: 'rgba(234, 88, 12, 0.3)',
    borderLight: 'rgba(234, 88, 12, 0.25)',
    bgDark: 'rgba(234, 88, 12, 0.15)',
    bgLight: 'rgba(234, 88, 12, 0.08)',
  },
  {
    id: 'artificial-intelligence',
    title: 'Artificial Intelligence',
    shortDescription: 'Search algorithms, heuristics, expert systems & knowledge graphs',
    iconName: 'Sparkles',
    gradient: 'from-violet-600 via-purple-600 to-indigo-600',
    accentHex: '#7c3aed',
    borderDark: 'rgba(124, 58, 237, 0.3)',
    borderLight: 'rgba(124, 58, 237, 0.25)',
    bgDark: 'rgba(124, 58, 237, 0.15)',
    bgLight: 'rgba(124, 58, 237, 0.08)',
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    shortDescription: 'Supervised, unsupervised, neural nets, regression & tensors',
    iconName: 'Brain',
    gradient: 'from-pink-600 via-rose-600 to-red-600',
    accentHex: '#db2777',
    borderDark: 'rgba(219, 39, 119, 0.3)',
    borderLight: 'rgba(219, 39, 119, 0.25)',
    bgDark: 'rgba(219, 39, 119, 0.15)',
    bgLight: 'rgba(219, 39, 119, 0.08)',
  },
  {
    id: 'cloud-computing',
    title: 'Cloud Computing',
    shortDescription: 'AWS, GCP, cloud infrastructure, serverless & virtualization',
    iconName: 'Cloud',
    gradient: 'from-sky-500 via-blue-500 to-indigo-600',
    accentHex: '#0284c7',
    borderDark: 'rgba(2, 132, 199, 0.3)',
    borderLight: 'rgba(2, 132, 199, 0.25)',
    bgDark: 'rgba(2, 132, 199, 0.15)',
    bgLight: 'rgba(2, 132, 199, 0.08)',
  },
  {
    id: 'system-design',
    title: 'System Design',
    shortDescription: 'Scalability, microservices, load balancing, caching & queues',
    iconName: 'Server',
    gradient: 'from-teal-600 via-emerald-600 to-cyan-600',
    accentHex: '#0d9488',
    borderDark: 'rgba(13, 148, 136, 0.3)',
    borderLight: 'rgba(13, 148, 136, 0.25)',
    bgDark: 'rgba(13, 148, 136, 0.15)',
    bgLight: 'rgba(13, 148, 136, 0.08)',
  },
  {
    id: 'competitive-programming',
    title: 'Competitive Programming',
    shortDescription: 'Advanced algorithmic techniques, math, complexity & contests',
    iconName: 'Trophy',
    gradient: 'from-amber-500 via-yellow-500 to-orange-600',
    accentHex: '#d97706',
    borderDark: 'rgba(217, 119, 6, 0.3)',
    borderLight: 'rgba(217, 119, 6, 0.25)',
    bgDark: 'rgba(217, 119, 6, 0.15)',
    bgLight: 'rgba(217, 119, 6, 0.08)',
  },
];

export const STUDY_RESOURCES_DATA: StudyResource[] = [
  // 1. C PROGRAMMING (Exact 5 Provided Resources)
  {
    id: 'c-codewithharry',
    title: 'C Language Tutorial for Beginners',
    channelOrAuthor: 'CodeWithHarry',
    category: 'c-programming',
    categoryLabel: 'C Programming',
    url: 'https://www.youtube.com/playlist?list=PLu0W_9lII9aiXlHcLx-mDH1Qul38wD3aR',
  },
  {
    id: 'c-freecodecamp',
    title: 'C Programming Full Course',
    channelOrAuthor: 'freeCodeCamp',
    category: 'c-programming',
    categoryLabel: 'C Programming',
    url: 'https://www.youtube.com/watch?v=KJgsSFOSQv0',
  },
  {
    id: 'c-jennys-lectures',
    title: 'C Programming Course',
    channelOrAuthor: "Jenny's Lectures",
    category: 'c-programming',
    categoryLabel: 'C Programming',
    url: 'https://www.youtube.com/playlist?list=PLdo5W4Nhv31a8UcMN9-35ghv8qyFWD9_S',
  },
  {
    id: 'c-apna-college',
    title: 'C Language Placement Course',
    channelOrAuthor: 'Apna College',
    category: 'c-programming',
    categoryLabel: 'C Programming',
    url: 'https://www.youtube.com/playlist?list=PLfqMhTWNBTe3H6c9OGXb5_6wcc1Mca52n',
  },
  {
    id: 'c-neso-academy',
    title: 'C Programming & Data Structures',
    channelOrAuthor: 'Neso Academy',
    category: 'c-programming',
    categoryLabel: 'C Programming',
    url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRhX6r2uhhlubuF5QextdCSM',
  },

  // 2. C++ PROGRAMMING (Exact 5 Provided Resources)
  {
    id: 'cpp-codewithharry',
    title: 'C++ Tutorials for Beginners',
    channelOrAuthor: 'CodeWithHarry',
    description: 'Detailed C++ playlist focusing on core logic and OOP principles.',
    category: 'cpp-programming',
    categoryLabel: 'C++ Programming',
    url: 'https://www.youtube.com/watch?v=yGB9jhsEsr8',
  },
  {
    id: 'cpp-apna-college',
    title: 'C++ Placement Course',
    channelOrAuthor: 'Apna College',
    description: 'Complete C++ course optimized for placement preparation and DSA.',
    category: 'cpp-programming',
    categoryLabel: 'C++ Programming',
    url: 'https://www.youtube.com/playlist?list=PLfqMhTWNBTe0b2nM6JHVCnAkhQRGiZMSJ',
  },
  {
    id: 'cpp-freecodecamp',
    title: 'C++ Full Course for Beginners',
    channelOrAuthor: 'freeCodeCamp',
    description: 'A comprehensive one-video tutorial covering all modern C++ concepts.',
    category: 'cpp-programming',
    categoryLabel: 'C++ Programming',
    url: 'https://youtu.be/8jLOx1hD3_o',
  },
  {
    id: 'cpp-abdul-bari',
    title: 'C++ Programming Mastery',
    channelOrAuthor: 'Abdul Bari',
    description: 'Excellent course focusing on deep conceptual understanding of C++.',
    category: 'cpp-programming',
    categoryLabel: 'C++ Programming',
    url: 'https://www.youtube.com/playlist?list=PLsr8vTgyLdy-LdXfLYZeskO2ERvsjjbk7',
  },
  {
    id: 'cpp-saurabh-shukla',
    title: 'C++ in Hindi',
    channelOrAuthor: 'Saurabh Shukla',
    description: 'Classic C++ playlist highly popular among Indian engineering students.',
    category: 'cpp-programming',
    categoryLabel: 'C++ Programming',
    url: 'https://www.youtube.com/playlist?list=PLLYz8uHU480j37APNXBdPz7YzAi4XlQUF',
  },

  // 3. PYTHON (Exact 5 Provided Resources)
  {
    id: 'python-codewithharry',
    title: '100 Days of Code Python',
    channelOrAuthor: 'CodeWithHarry',
    description: 'A complete 100-day Python boot camp covering projects and core concepts.',
    category: 'python',
    categoryLabel: 'Python',
    url: 'https://www.youtube.com/playlist?list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg',
  },
  {
    id: 'python-freecodecamp',
    title: 'Python for Beginners Full Course',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Extremely popular long-form Python video covering all fundamentals.',
    category: 'python',
    categoryLabel: 'Python',
    url: 'https://www.youtube.com/watch?v=rfscVS0vtbw',
  },
  {
    id: 'python-mosh',
    title: 'Python Tutorial for Beginners',
    channelOrAuthor: 'Programming with Mosh',
    description: 'Clean and engaging crash course for Python fundamentals.',
    category: 'python',
    categoryLabel: 'Python',
    url: 'https://www.youtube.com/watch?v=_uQrJ0TkZlc',
  },
  {
    id: 'python-telusko',
    title: 'Python Programming Complete',
    channelOrAuthor: 'Telusko',
    description: 'Structured programming tutorials perfect for university students.',
    category: 'python',
    categoryLabel: 'Python',
    url: 'https://www.youtube.com/playlist?list=PLsyeobzWxl7poL9JTVyndKe62ieoN-MZ3',
  },
  {
    id: 'python-apna-college',
    title: 'Python Placement Course',
    channelOrAuthor: 'Apna College',
    description: 'Beginner-friendly Python concepts mapped for campus placements.',
    category: 'python',
    categoryLabel: 'Python',
    url: 'https://www.youtube.com/watch?v=vLqTf2b6GZw',
  },

  // 4. JAVA (Exact 5 Provided Resources)
  {
    id: 'java-apna-college',
    title: 'Java Placement Course',
    channelOrAuthor: 'Apna College',
    description: 'The definitive Java programming course for placements and coding rounds.',
    category: 'java',
    categoryLabel: 'Java',
    url: 'https://www.youtube.com/playlist?list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop',
  },
  {
    id: 'java-kunal-kushwaha',
    title: 'Java Tutorial for Beginners',
    channelOrAuthor: 'Kunal Kushwaha',
    description: 'Thorough Java course focusing on memory management and core mechanics.',
    category: 'java',
    categoryLabel: 'Java',
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ',
  },
  {
    id: 'java-freecodecamp',
    title: 'Java Full Course',
    channelOrAuthor: 'freeCodeCamp',
    description: 'An excellent, fast-paced complete Java learning video.',
    category: 'java',
    categoryLabel: 'Java',
    url: 'https://www.youtube.com/watch?v=eIrMbAQSU34',
  },
  {
    id: 'java-telusko',
    title: 'Java Programming Tutorials',
    channelOrAuthor: 'Telusko',
    description: 'Highly visual and easy-to-understand complete Java playlist.',
    category: 'java',
    categoryLabel: 'Java',
    url: 'https://www.youtube.com/playlist?list=PLsyeobzWxl7pe_IiTfNyr55kwJPWbgxB5',
  },
  {
    id: 'java-codewithharry',
    title: 'Java Tutorials in Hindi',
    channelOrAuthor: 'CodeWithHarry',
    description: 'Beginner-focused Java learning track in Hindi.',
    category: 'java',
    categoryLabel: 'Java',
    url: 'https://www.youtube.com/playlist?list=PLu0W_9lII9agS67Uits0UnJyrYiXhDS6q',
  },

  // 5. DATA STRUCTURES & ALGORITHMS (Exact 5 Provided Resources)
  {
    id: 'dsa-takeuforward',
    title: "Striver's A2Z DSA Course",
    channelOrAuthor: 'Take U Forward',
    description: 'The absolute standard for DSA prep and competitive coding.',
    category: 'dsa',
    categoryLabel: 'Data Structures & Algorithms',
    url: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz',
  },
  {
    id: 'dsa-love-babbar',
    title: 'DSA Placement Course',
    channelOrAuthor: 'Love Babbar',
    description: 'Highly energetic and exhaustive DSA bootcamp in Hindi/Hinglish.',
    category: 'dsa',
    categoryLabel: 'Data Structures & Algorithms',
    url: 'https://www.youtube.com/playlist?list=PLDzeHZWIZsTryvtXdMr6rPh4IDexB5NIA',
  },
  {
    id: 'dsa-abdul-bari',
    title: 'Algorithms Masterclass',
    channelOrAuthor: 'Abdul Bari',
    description: 'In-depth whiteboard lectures on algorithm analysis and design.',
    category: 'dsa',
    categoryLabel: 'Data Structures & Algorithms',
    url: 'https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
  },
  {
    id: 'dsa-kunal-kushwaha',
    title: 'Data Structures & Algorithms in Java',
    channelOrAuthor: 'Kunal Kushwaha',
    description: 'Complete open-source DSA bootcamp utilizing Java.',
    category: 'dsa',
    categoryLabel: 'Data Structures & Algorithms',
    url: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnr_DxHsP7AW9ftq0AtAyYqJ',
  },
  {
    id: 'dsa-apna-college',
    title: 'DSA in C++',
    channelOrAuthor: 'Apna College',
    description: 'Targeted DSA series for top product-based company interviews.',
    category: 'dsa',
    categoryLabel: 'Data Structures & Algorithms',
    url: 'https://www.youtube.com/playlist?list=PLfqMhTWNBTe137I_EPQd34TsgV6IO55pt',
  },

  // 6. OBJECT-ORIENTED PROGRAMMING (OOP) (Exact Provided Resources)
  {
    id: 'oops-love-babbar',
    title: 'OOPs in C++ Complete',
    channelOrAuthor: 'Love Babbar',
    description: 'Intense one-shot style video covering OOPs concepts for interviews.',
    category: 'oops',
    categoryLabel: 'Object-Oriented Programming',
    url: 'https://www.youtube.com/watch?v=JeYx8vJB75Q',
  },
  {
    id: 'oops-freecodecamp',
    title: 'Object-Oriented Programming',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Comprehensive breakdown of all OOP principles in programming.',
    category: 'oops',
    categoryLabel: 'Object-Oriented Programming',
    url: 'https://www.youtube.com/watch?v=pTB0EiLXUC8',
  },
  {
    id: 'oops-codebeauty',
    title: 'OOP in C++',
    channelOrAuthor: 'CodeBeauty',
    description: 'Very clear and concise explanations of polymorphism, inheritance, and encapsulation.',
    category: 'oops',
    categoryLabel: 'Object-Oriented Programming',
    url: 'https://www.youtube.com/watch?v=wN0x9eZLix4',
  },
  {
    id: 'oops-kunal-kushwaha',
    title: 'Object Oriented Programming in Java',
    channelOrAuthor: 'Kunal Kushwaha',
    description: 'Deep dive into OOP concepts using Java.',
    category: 'oops',
    categoryLabel: 'Object-Oriented Programming',
    url: 'https://www.youtube.com/watch?v=BSVKUk58K6U',
  },

  // 7. DATABASE MANAGEMENT SYSTEMS (DBMS) (Exact Provided Resources)
  {
    id: 'dbms-gate-smashers',
    title: 'DBMS Complete Playlist',
    channelOrAuthor: 'Gate Smashers',
    description: 'The ultimate DBMS series for university exams and GATE preparation.',
    category: 'dbms',
    categoryLabel: 'DBMS',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y',
  },
  {
    id: 'dbms-neso-academy',
    title: 'Database Management System',
    channelOrAuthor: 'Neso Academy',
    description: 'High-quality, academic-level lectures on relational databases.',
    category: 'dbms',
    categoryLabel: 'DBMS',
    url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRiyryTrbKHX1Sh9luYI0dhX',
  },
  {
    id: 'dbms-jennys-lectures',
    title: 'DBMS Tutorials',
    channelOrAuthor: "Jenny's Lectures",
    description: 'Easy-to-understand DBMS concepts tailored for beginners.',
    category: 'dbms',
    categoryLabel: 'DBMS',
    url: 'https://www.youtube.com/playlist?list=PLdo5W4Nhv31b33kF46f9aFjoJPOkdlsRc',
  },
  {
    id: 'dbms-knowledge-gate',
    title: 'DBMS Complete Course',
    channelOrAuthor: 'Knowledge Gate',
    description: 'In-depth coverage of normal forms, SQL, and transaction management.',
    category: 'dbms',
    categoryLabel: 'DBMS',
    url: 'https://www.youtube.com/watch?v=YRnjGeQbsHQ&list=PLmXKhU9FNesR1rSES7oLdJaNFgmuj0SYV',
  },
  {
    id: 'dbms-freecodecamp',
    title: 'Database Design Full Course',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Practical guide to designing databases and writing SQL.',
    category: 'dbms',
    categoryLabel: 'DBMS',
    url: 'https://www.youtube.com/watch?v=ztHopE5Wnpc',
  },

  // 8. OPERATING SYSTEMS (Exact Provided Resources)
  {
    id: 'os-gate-smashers',
    title: 'Operating System',
    channelOrAuthor: 'Gate Smashers',
    description: 'Top-rated OS playlist covering scheduling, deadlocks, and memory.',
    category: 'operating-systems',
    categoryLabel: 'Operating Systems',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p',
  },
  {
    id: 'os-neso-academy',
    title: 'Operating System Tutorials',
    channelOrAuthor: 'Neso Academy',
    description: 'Excellent academic OS course with clear diagrams and examples.',
    category: 'operating-systems',
    categoryLabel: 'Operating Systems',
    url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRiVhbXDGLXDk_OQAeuVcp2O',
  },
  {
    id: 'os-jennys-lectures',
    title: 'Operating Systems Playlist',
    channelOrAuthor: "Jenny's Lectures",
    description: 'Simplified breakdown of core OS concepts for engineering students.',
    category: 'operating-systems',
    categoryLabel: 'Operating Systems',
    url: 'https://www.youtube.com/playlist?list=PLdo5W4Nhv31a5ucW_S1K3-x6ztBRD-PNa',
  },
  {
    id: 'os-knowledge-gate',
    title: 'Operating System',
    channelOrAuthor: 'Knowledge Gate',
    description: 'Detailed university-level operating systems lectures.',
    category: 'operating-systems',
    categoryLabel: 'Operating Systems',
    url: 'https://www.youtube.com/watch?v=009FHqBo87Q&list=PLmXKhU9FNesSFvj6gASuWmQd23Ul5omtD',
  },
  {
    id: 'os-love-babbar',
    title: 'Operating System Interview Crash Course',
    channelOrAuthor: 'Love Babbar',
    description: 'A great summary of OS topics tailored specifically for placement interviews.',
    category: 'operating-systems',
    categoryLabel: 'Operating Systems',
    url: 'https://www.youtube.com/watch?v=_TpOHMCODXo&list=PLDzeHZWIZsTr3nwuTegHLa2qlI81QweYG',
  },

  // 9. COMPUTER NETWORKS (Exact Provided Resources)
  {
    id: 'cn-gate-smashers',
    title: 'Computer Networks',
    channelOrAuthor: 'Gate Smashers',
    description: 'Standard CN playlist heavily used by Indian students for exams.',
    category: 'computer-networks',
    categoryLabel: 'Computer Networks',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGFBD2-2joCpWOLUrDLvVV_',
  },
  {
    id: 'cn-neso-academy',
    title: 'Computer Networks',
    channelOrAuthor: 'Neso Academy',
    description: 'Extremely professional breakdown of the OSI model and protocols.',
    category: 'computer-networks',
    categoryLabel: 'Computer Networks',
    url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRgMCUAG0XRw78UA8qnv6jEx',
  },
  {
    id: 'cn-freecodecamp',
    title: 'Computer Networking Full Course',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Practical and theoretical networking fundamentals in one long video.',
    category: 'computer-networks',
    categoryLabel: 'Computer Networks',
    url: 'https://www.youtube.com/watch?v=qiQR5rTSshw',
  },
  {
    id: 'cn-knowledge-gate',
    title: 'Computer Networks Series',
    channelOrAuthor: 'Knowledge Gate',
    description: 'In-depth syllabus coverage for engineering CN courses.',
    category: 'computer-networks',
    categoryLabel: 'Computer Networks',
    url: 'https://www.youtube.com/watch?v=q3Z3Qa1UNBA&list=PLmXKhU9FNesSjFbXSZGF8JF_4LVwwofCd',
  },
  {
    id: 'cn-networkchuck',
    title: 'Free CCNA / Networking',
    channelOrAuthor: 'NetworkChuck',
    description: 'Fun, practical, and heavily engaging networking tutorials.',
    category: 'computer-networks',
    categoryLabel: 'Computer Networks',
    url: 'https://www.youtube.com/playlist?list=PLIhvC56v63IJVXv0GJcl9vO5Z6znCVb1P',
  },

  // 10. COMPUTER ORGANIZATION & ARCHITECTURE (COA) (Exact Provided Resources)
  {
    id: 'coa-gate-smashers',
    title: 'Computer Architecture',
    channelOrAuthor: 'Gate Smashers',
    description: 'Bite-sized, exam-focused COA videos.',
    category: 'coa',
    categoryLabel: 'COA',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHMonh3G6QNKq53C6oNXGrX',
  },
  {
    id: 'coa-neso-academy',
    title: 'Computer Organization & Architecture',
    channelOrAuthor: 'Neso Academy',
    description: 'Detailed hardware and architecture logic tutorials.',
    category: 'coa',
    categoryLabel: 'COA',
    url: 'https://www.youtube.com/watch?v=Ol8D69VKX2k&list=PLBlnK6fEyqRgLLlzdgiTUKULKJPYc0A4q',
  },
  {
    id: 'coa-knowledge-gate',
    title: 'Computer Architecture',
    channelOrAuthor: 'Knowledge Gate',
    description: 'Extensive coverage of microprocessors, pipelines, and memory hierarchy.',
    category: 'coa',
    categoryLabel: 'COA',
    url: 'https://www.youtube.com/watch?v=DsK35f8wyUw&list=PLmXKhU9FNesS4B30OmgxP7nrzq1UhiMiv',
  },
  {
    id: 'coa-education-4u',
    title: 'Computer Organization',
    channelOrAuthor: 'Education 4u',
    description: 'Classic whiteboard lectures for semester exam preparation.',
    category: 'coa',
    categoryLabel: 'COA',
    url: 'https://www.youtube.com/watch?v=v4O2cj3Oe0A&list=PLrjkTql3jnm8AcFgkc5TE_yQgeHEuKYrG',
  },
  {
    id: 'coa-well-academy',
    title: 'COA Lectures',
    channelOrAuthor: 'Well Academy',
    description: 'Comprehensive playlist covering core organization topics.',
    category: 'coa',
    categoryLabel: 'COA',
    url: 'https://www.youtube.com/watch?v=NV9QD40vgLU&list=PL9zFgBale5fsVaOVUqXA1cJ22ePKpDEim',
  },

  // 11. THEORY OF COMPUTATION (TOC) / AUTOMATA (Exact Provided Resources)
  {
    id: 'toc-gate-smashers',
    title: 'Theory of Computation',
    channelOrAuthor: 'Gate Smashers',
    description: 'The most popular TOC and Automata theory playlist in India.',
    category: 'toc-automata',
    categoryLabel: 'TOC / Automata',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i',
  },
  {
    id: 'toc-neso-academy',
    title: 'Theory of Computation',
    channelOrAuthor: 'Neso Academy',
    description: 'High-quality, step-by-step logic and automata breakdowns.',
    category: 'toc-automata',
    categoryLabel: 'TOC / Automata',
    url: 'https://www.youtube.com/watch?v=58N2N7zJGrQ&list=PLBlnK6fEyqRgp46KUv4ZY69yXmpwKOIev',
  },
  {
    id: 'toc-knowledge-gate',
    title: 'Theory of Computation',
    channelOrAuthor: 'Knowledge Gate',
    description: 'Complete syllabus coverage for GATE and university TOC exams.',
    category: 'toc-automata',
    categoryLabel: 'TOC / Automata',
    url: 'https://www.youtube.com/watch?v=9kuynHcM3UA&list=PLmXKhU9FNesSdCsn6YQqu9DmXRMsYdZ2T',
  },
  {
    id: 'toc-education-4u',
    title: 'Automata Theory',
    channelOrAuthor: 'Education 4u',
    description: 'Thorough coverage of DFA, NFA, PDA, and Turing Machines.',
    category: 'toc-automata',
    categoryLabel: 'TOC / Automata',
    url: 'https://www.youtube.com/watch?v=dCiZZiqVv9w&list=PLrjkTql3jnm_TWSXXvWX1_jX-L6f1QJSx',
  },
  {
    id: 'toc-easy-engineering',
    title: 'TOC Full Course',
    channelOrAuthor: 'Easy Engineering Classes',
    description: 'Simplified approach to formal languages and automata.',
    category: 'toc-automata',
    categoryLabel: 'TOC / Automata',
    url: 'https://www.youtube.com/watch?v=iD6u_2iNnu0&list=PLV8vIYTIdSnZYVUJ6duL_ulTsmVQmmd74',
  },

  // 12. COMPILER DESIGN (Exact Provided Resources)
  {
    id: 'compiler-gate-smashers',
    title: 'Compiler Design',
    channelOrAuthor: 'Gate Smashers',
    description: 'Crucial playlist bridging TOC knowledge into compiler phases.',
    category: 'compiler-design',
    categoryLabel: 'Compiler Design',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEKtKSIHYusizkESC42diyc',
  },
  {
    id: 'compiler-neso-academy',
    title: 'Compiler Design',
    channelOrAuthor: 'Neso Academy',
    description: 'Detailed tutorials on parsing, lexers, and syntax analysis.',
    category: 'compiler-design',
    categoryLabel: 'Compiler Design',
    url: 'https://www.youtube.com/watch?v=5ZmFlxrNaN8&list=PLBlnK6fEyqRjT3oJxFXRgjPNzeS-LFY-q',
  },
  {
    id: 'compiler-knowledge-gate',
    title: 'Compiler Design Series',
    channelOrAuthor: 'Knowledge Gate',
    description: 'In-depth lectures focusing on bottom-up and top-down parsers.',
    category: 'compiler-design',
    categoryLabel: 'Compiler Design',
    url: 'https://www.youtube.com/playlist?list=PLmXKhU9FNesSmu-_DKC7APRoFkaQvGurx',
  },
  {
    id: 'compiler-education-4u',
    title: 'Compiler Design Tutorials',
    channelOrAuthor: 'Education 4u',
    description: 'Great resource for college compiler design exams.',
    category: 'compiler-design',
    categoryLabel: 'Compiler Design',
    url: 'https://www.youtube.com/watch?v=KBulg_u-b3w&list=PLrjkTql3jnm-wW5XdvumCa1u9LjczipjA',
  },
  {
    id: 'compiler-easy-engineering',
    title: 'Compiler Design Complete',
    channelOrAuthor: 'Easy Engineering Classes',
    description: 'Short, to-the-point videos covering essential compiler topics.',
    category: 'compiler-design',
    categoryLabel: 'Compiler Design',
    url: 'https://www.youtube.com/watch?v=hRM9ZvjbpVY&list=PLV8vIYTIdSnaeEO7C3elIV9u-Vj5G5CRF',
  },

  // 13. WEB DEVELOPMENT (Exact 5 Provided Resources)
  {
    id: 'web-codewithharry',
    title: 'Web Development Complete Course',
    channelOrAuthor: 'CodeWithHarry',
    description: 'Full stack web dev boot camp covering HTML, CSS, JS, and backend.',
    category: 'web-development',
    categoryLabel: 'Web Development',
    url: 'https://www.youtube.com/playlist?list=PLu0W_9lII9agiCUZYRsvtGTXdxkzPyItg',
  },
  {
    id: 'web-freecodecamp',
    title: 'Full Stack Web Development',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Extensive project-based course building modern web applications.',
    category: 'web-development',
    categoryLabel: 'Web Development',
    url: 'https://www.youtube.com/watch?v=nu_pCVPKzTk',
  },
  {
    id: 'web-apna-college',
    title: 'Web Development Delta',
    channelOrAuthor: 'Apna College',
    description: 'Comprehensive web development guide tailored for tech placements.',
    category: 'web-development',
    categoryLabel: 'Web Development',
    url: 'https://www.youtube.com/watch?v=l1EssrLxt7E',
  },
  {
    id: 'web-mosh',
    title: 'HTML & CSS Full Course',
    channelOrAuthor: 'Programming with Mosh',
    description: 'Clean and engaging crash course focusing on frontend foundations.',
    category: 'web-development',
    categoryLabel: 'Web Development',
    url: 'https://www.youtube.com/watch?v=qz0aGYrrlhU',
  },
  {
    id: 'web-traversy-media',
    title: 'Web Dev Crash Course',
    channelOrAuthor: 'Traversy Media',
    description: 'Fast-paced web dev introduction from a top industry instructor.',
    category: 'web-development',
    categoryLabel: 'Web Development',
    url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
  },

  // 14. SOFTWARE ENGINEERING (Exact Provided Resources)
  {
    id: 'se-gate-smashers',
    title: 'Software Engineering',
    channelOrAuthor: 'Gate Smashers',
    description: 'Great coverage of SDLC, agile, and software models for exams.',
    category: 'software-engineering',
    categoryLabel: 'Software Engineering',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiEed7SKZBnC6ypFDWYLRvB2',
  },
  {
    id: 'se-knowledge-gate',
    title: 'Software Engineering',
    channelOrAuthor: 'Knowledge Gate',
    description: 'In-depth course on software testing, metrics, and project management.',
    category: 'software-engineering',
    categoryLabel: 'Software Engineering',
    url: 'https://www.youtube.com/watch?v=NlLM3sVF8wY&list=PLmXKhU9FNesTrw7n8ouPsSLEcduRlENHr',
  },
  {
    id: 'se-education-4u',
    title: 'Software Engineering Complete',
    channelOrAuthor: 'Education 4u',
    description: 'Structured engineering principles explained for university students.',
    category: 'software-engineering',
    categoryLabel: 'Software Engineering',
    url: 'https://www.youtube.com/watch?v=WxkP5KR_Emk&list=PLrjkTql3jnm9b5nr-ggx7Pt1G4UAHeFlJ',
  },
  {
    id: 'se-jennys-lectures',
    title: 'Software Engineering Tutorials',
    channelOrAuthor: "Jenny's Lectures",
    description: 'Simple and clear explanations of core software engineering concepts.',
    category: 'software-engineering',
    categoryLabel: 'Software Engineering',
    url: 'https://www.youtube.com/watch?v=8jH07r6135o&list=PL_pbwdIyffslgxMVyXhnHiSn_EWTvx1G-',
  },
  {
    id: 'se-freecodecamp',
    title: 'Software Engineering Tutorial',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Practical industry-level software engineering concepts.',
    category: 'software-engineering',
    categoryLabel: 'Software Engineering',
    url: 'https://www.youtube.com/watch?v=F2FmTdLtb_4',
  },

  // 15. GIT & GITHUB (Exact Provided Resources)
  {
    id: 'git-codewithharry',
    title: 'Git & GitHub Tutorial',
    channelOrAuthor: 'CodeWithHarry',
    description: 'Beginner-friendly explanation of version control in Hindi.',
    category: 'git-github',
    categoryLabel: 'Git & GitHub',
    url: 'https://www.youtube.com/watch?v=gwWKnnCMQ5c',
  },
  {
    id: 'git-apna-college',
    title: 'Git and GitHub Complete Course',
    channelOrAuthor: 'Apna College',
    description: 'Essential version control concepts geared toward college students.',
    category: 'git-github',
    categoryLabel: 'Git & GitHub',
    url: 'https://www.youtube.com/watch?v=Ez8F0nW6S-w',
  },
  {
    id: 'git-kunal-kushwaha',
    title: 'Complete Git and GitHub Course',
    channelOrAuthor: 'Kunal Kushwaha',
    description: 'Extensive open-source focused Git tutorial.',
    category: 'git-github',
    categoryLabel: 'Git & GitHub',
    url: 'https://www.youtube.com/watch?v=apGV9Kg7ics',
  },
  {
    id: 'git-freecodecamp',
    title: 'Git and GitHub for Beginners',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Practical step-by-step crash course on version control.',
    category: 'git-github',
    categoryLabel: 'Git & GitHub',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
  },
  {
    id: 'git-mosh',
    title: 'Git Tutorial for Beginners',
    channelOrAuthor: 'Programming with Mosh',
    description: 'Visual and concise explanation of how Git branches and commits work.',
    category: 'git-github',
    categoryLabel: 'Git & GitHub',
    url: 'https://www.youtube.com/watch?v=8JJ101D3knE',
  },

  // 16. ARTIFICIAL INTELLIGENCE (Exact Provided Resources)
  {
    id: 'ai-gate-smashers',
    title: 'Artificial Intelligence',
    channelOrAuthor: 'Gate Smashers',
    description: 'Excellent exam-oriented playlist for AI algorithms and search techniques.',
    category: 'artificial-intelligence',
    categoryLabel: 'Artificial Intelligence',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHGhOHV-nwb0HR5US5GFKFI',
  },
  {
    id: 'ai-edureka',
    title: 'AI Full Course',
    channelOrAuthor: 'Edureka',
    description: 'Long-form video covering AI basics, deep learning, and NLP.',
    category: 'artificial-intelligence',
    categoryLabel: 'Artificial Intelligence',
    url: 'https://www.youtube.com/watch?v=JMUxmLyrhSk',
  },
  {
    id: 'ai-knowledge-gate',
    title: 'Artificial Intelligence Complete',
    channelOrAuthor: 'Knowledge Gate',
    description: 'Comprehensive academic coverage of AI problem solving and logic.',
    category: 'artificial-intelligence',
    categoryLabel: 'Artificial Intelligence',
    url: 'https://www.youtube.com/playlist?list=PLmXKhU9FNe10aXoY2O1vQjN9U51bCq48p',
  },
  {
    id: 'ai-simplilearn',
    title: 'Artificial Intelligence Full Course',
    channelOrAuthor: 'Simplilearn',
    description: 'Industry-focused introduction to modern AI systems.',
    category: 'artificial-intelligence',
    categoryLabel: 'Artificial Intelligence',
    url: 'https://www.youtube.com/watch?v=ad79nYk2keg',
  },
  {
    id: 'ai-nptel',
    title: 'AI Course',
    channelOrAuthor: 'NPTEL',
    description: 'Rigorous university-level curriculum backed by IIT professors.',
    category: 'artificial-intelligence',
    categoryLabel: 'Artificial Intelligence',
    url: 'https://www.youtube.com/watch?v=GHpchgLoDvI&list=PLp6ek2hDcoNB_YJCruBFjhF79f5ZHyBuz',
  },

  // 17. MACHINE LEARNING (Exact Provided Resources)
  {
    id: 'ml-krish-naik',
    title: 'Complete Machine Learning Playlist',
    channelOrAuthor: 'Krish Naik',
    description: 'The most practical, project-driven ML series on YouTube.',
    category: 'machine-learning',
    categoryLabel: 'Machine Learning',
    url: 'https://www.youtube.com/playlist?list=PLZoTAELRMXVPBTrWtJkn3wWQxZkmTXGwe',
  },
  {
    id: 'ml-freecodecamp',
    title: 'Machine Learning for Everybody',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Fantastic beginner-friendly ML course covering real-world data.',
    category: 'machine-learning',
    categoryLabel: 'Machine Learning',
    url: 'https://www.youtube.com/watch?v=i_LwzRVP7bg',
  },
  {
    id: 'ml-codewithharry',
    title: 'Machine Learning Tutorial',
    channelOrAuthor: 'CodeWithHarry',
    description: 'Great starting point for ML and data science in Hindi.',
    category: 'machine-learning',
    categoryLabel: 'Machine Learning',
    url: 'https://www.youtube.com/playlist?list=PLu0W_9lII9ai6fAMHp-acBmJONT7Y4BSG',
  },
  {
    id: 'ml-stanford-online',
    title: 'Stanford Machine Learning',
    channelOrAuthor: 'Stanford Online',
    description: 'The world-famous Andrew Ng ML course uploaded for free.',
    category: 'machine-learning',
    categoryLabel: 'Machine Learning',
    url: 'https://www.youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU',
  },
  {
    id: 'ml-simplilearn',
    title: 'Machine Learning Full Course',
    channelOrAuthor: 'Simplilearn',
    description: 'Comprehensive bootcamp-style video covering regression to neural networks.',
    category: 'machine-learning',
    categoryLabel: 'Machine Learning',
    url: 'https://www.youtube.com/watch?v=ukzFI9rgwfU',
  },

  // 18. CLOUD COMPUTING (Exact Provided Resources)
  {
    id: 'cloud-freecodecamp',
    title: 'AWS Certified Cloud Practitioner',
    channelOrAuthor: 'freeCodeCamp',
    description: 'The best completely free certification prep and cloud intro course.',
    category: 'cloud-computing',
    categoryLabel: 'Cloud Computing',
    url: 'https://www.youtube.com/watch?v=3hLmDS179YE',
  },
  {
    id: 'cloud-edureka',
    title: 'Cloud Computing Full Course',
    channelOrAuthor: 'Edureka',
    description: 'Thorough overview of IaaS, PaaS, SaaS, and cloud models.',
    category: 'cloud-computing',
    categoryLabel: 'Cloud Computing',
    url: 'https://www.youtube.com/watch?v=EN4fEbcFZ_E',
  },
  {
    id: 'cloud-gate-smashers',
    title: 'Cloud Computing Complete',
    channelOrAuthor: 'Gate Smashers',
    description: 'Academic syllabus-focused playlist on cloud architectures.',
    category: 'cloud-computing',
    categoryLabel: 'Cloud Computing',
    url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiHRHVUtR-O52MsrdUSrzuy4',
  },
  {
    id: 'cloud-simplilearn',
    title: 'Cloud Computing Tutorial',
    channelOrAuthor: 'Simplilearn',
    description: 'Great overview of major cloud providers and deployment models.',
    category: 'cloud-computing',
    categoryLabel: 'Cloud Computing',
    url: 'https://www.youtube.com/watch?v=M988_fsOSWo',
  },
  {
    id: 'cloud-tech-with-tim',
    title: 'Cloud Computing Concepts',
    channelOrAuthor: 'Tech With Tim',
    description: 'Simplified primer on how the cloud works for developers.',
    category: 'cloud-computing',
    categoryLabel: 'Cloud Computing',
    url: 'https://www.youtube.com/watch?v=6l88XYUjNIs&list=PLYwpaL_SFmcCyQH0n9GHfwviu6KeJ46BV',
  },

  // 19. SYSTEM DESIGN (Exact Provided Resources)
  {
    id: 'sd-gaurav-sen',
    title: 'System Design',
    channelOrAuthor: 'Gaurav Sen',
    description: 'The absolute gold standard for understanding large-scale systems in India.',
    category: 'system-design',
    categoryLabel: 'System Design',
    url: 'https://www.youtube.com/watch?v=SqcXvc3ZmRU&list=PLMCXHnjXnTnvo6alSjVkgxV-VH6EPyvoX',
  },
  {
    id: 'sd-freecodecamp',
    title: 'System Design Interview Prep',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Extensive system design crash course for cracking tech interviews.',
    category: 'system-design',
    categoryLabel: 'System Design',
    url: 'https://www.youtube.com/watch?v=bUHFg8CZFws',
  },
  {
    id: 'sd-bytebytego',
    title: 'System Design Fundamentals',
    channelOrAuthor: 'ByteByteGo',
    description: 'Highly visual breakdowns of modern application architectures.',
    category: 'system-design',
    categoryLabel: 'System Design',
    url: 'https://www.youtube.com/watch?v=lX4CrbXMsNQ&list=PLCRMIe5FDPsd0gVs500xeOewfySTsmEjf',
  },
  {
    id: 'sd-shreyansh',
    title: 'System Design Complete Course',
    channelOrAuthor: 'Concept&Coding by Shreyansh',
    description: 'Excellent LLD and HLD concepts explained by an industry expert.',
    category: 'system-design',
    categoryLabel: 'System Design',
    url: 'https://www.youtube.com/playlist?list=PL6W8uoQQ2c61X_9e6Net0WdYZidm7zooW',
  },
  {
    id: 'sd-codekarle',
    title: 'System Design Tutorials',
    channelOrAuthor: 'CodeKarle',
    description: 'In-depth case studies of designing apps like Uber, WhatsApp, and Netflix.',
    category: 'system-design',
    categoryLabel: 'System Design',
    url: 'https://www.youtube.com/watch?v=EpASu_1dUdE&list=PLhgw50vUymyckXl3D1IlXoVl94wknJfUC',
  },

  // 20. COMPETITIVE PROGRAMMING (Exact Provided Resources)
  {
    id: 'cp-luv',
    title: 'Competitive Programming Course',
    channelOrAuthor: 'Luv',
    description: 'The most complete CP-focused C++ course covering advanced math and graphs.',
    category: 'competitive-programming',
    categoryLabel: 'Competitive Programming',
    url: 'https://www.youtube.com/watch?v=lHJcLLsre70&list=PLauivoElc3gh48CgP4cQPrC1wrpAqY9cf',
  },
  {
    id: 'cp-takeuforward',
    title: 'Dynamic Programming / CP',
    channelOrAuthor: 'Take U Forward',
    description: 'Top-tier logic building playlist necessary for competitive coding.',
    category: 'competitive-programming',
    categoryLabel: 'Competitive Programming',
    url: 'https://www.youtube.com/watch?v=tyB0ztf0DNY&list=PLgUwDviBIf0pwFf-BnpkXxs0Ra0eU2sJY',
  },
  {
    id: 'cp-codencode',
    title: 'Competitive Programming Concepts',
    channelOrAuthor: 'CodeNCode',
    description: 'Deep dive into number theory and graph theory for CP.',
    category: 'competitive-programming',
    categoryLabel: 'Competitive Programming',
    url: 'https://www.youtube.com/watch?v=6ZBY9yGNWbI&list=PLzjZaW71kMwTGbP1suqY16w1VSb9ZNuvE',
  },
  {
    id: 'cp-freecodecamp',
    title: 'Competitive Programming Full Course',
    channelOrAuthor: 'freeCodeCamp',
    description: 'Long-form video breaking down CP tricks and fast algorithms.',
    category: 'competitive-programming',
    categoryLabel: 'Competitive Programming',
    url: 'https://www.youtube.com/watch?v=tw1vExHbjWM&list=PLxgZQoSe9cg0-p9RHvaf32XoFEHT_2tj2',
  },
  {
    id: 'cp-aditya-verma',
    title: 'Dynamic Programming Complete Course',
    channelOrAuthor: 'Aditya Verma',
    description: 'High-level problem-solving tactics by a top-rated competitive coder.',
    category: 'competitive-programming',
    categoryLabel: 'Competitive Programming',
    url: 'https://www.youtube.com/watch?v=nqowUJzG-iM&list=PL_z_8CaSLPWekqhdCPmFohncHwz8TY2Go',
  },
];
