export interface AITool {
  id: string;
  name: string;
  category: 'chatbots' | 'video' | 'image' | 'presentation' | 'website';
  categoryLabel: string;
  url: string;
  iconName: string;
  accentColor: string;
  gradient: string;
}

export interface AICategory {
  id: 'chatbots' | 'video' | 'image' | 'presentation' | 'website';
  title: string;
  shortDescription: string;
  iconName: string;
  colorName: 'violet' | 'cyan' | 'pink' | 'amber' | 'emerald';
  gradient: string;
  accentHex: string;
  bgLight: string;
  bgDark: string;
  borderLight: string;
  borderDark: string;
}

export const AI_CATEGORIES: AICategory[] = [
  {
    id: 'chatbots',
    title: 'AI Chatbots',
    shortDescription: 'Conversational AI, reasoning & intelligence',
    iconName: 'MessageSquareText',
    colorName: 'violet',
    gradient: 'from-violet-500 via-indigo-500 to-purple-600',
    accentHex: '#8b5cf6',
    bgLight: 'rgba(139, 92, 246, 0.08)',
    bgDark: 'rgba(139, 92, 246, 0.15)',
    borderLight: 'rgba(139, 92, 246, 0.25)',
    borderDark: 'rgba(139, 92, 246, 0.3)',
  },
  {
    id: 'video',
    title: 'AI Video Generation',
    shortDescription: 'Cinematic text-to-video & visual motion',
    iconName: 'Video',
    colorName: 'cyan',
    gradient: 'from-cyan-500 via-sky-500 to-blue-600',
    accentHex: '#06b6d4',
    bgLight: 'rgba(6, 182, 212, 0.08)',
    bgDark: 'rgba(6, 182, 212, 0.15)',
    borderLight: 'rgba(6, 182, 212, 0.25)',
    borderDark: 'rgba(6, 182, 212, 0.3)',
  },
  {
    id: 'image',
    title: 'AI Image Generation',
    shortDescription: 'Photorealistic art & creative design generation',
    iconName: 'Image',
    colorName: 'pink',
    gradient: 'from-pink-500 via-rose-500 to-fuchsia-600',
    accentHex: '#ec4899',
    bgLight: 'rgba(236, 72, 153, 0.08)',
    bgDark: 'rgba(236, 72, 153, 0.15)',
    borderLight: 'rgba(236, 72, 153, 0.25)',
    borderDark: 'rgba(236, 72, 153, 0.3)',
  },
  {
    id: 'presentation',
    title: 'AI Presentation Generation',
    shortDescription: 'AI slide decks, decks formatting & storyboards',
    iconName: 'Presentation',
    colorName: 'amber',
    gradient: 'from-amber-500 via-orange-500 to-yellow-600',
    accentHex: '#f59e0b',
    bgLight: 'rgba(245, 158, 11, 0.08)',
    bgDark: 'rgba(245, 158, 11, 0.15)',
    borderLight: 'rgba(245, 158, 11, 0.25)',
    borderDark: 'rgba(245, 158, 11, 0.3)',
  },
  {
    id: 'website',
    title: 'AI Website Generation',
    shortDescription: 'Modern web design, full-stack builders & CMS',
    iconName: 'Globe',
    colorName: 'emerald',
    gradient: 'from-emerald-500 via-teal-500 to-cyan-600',
    accentHex: '#10b981',
    bgLight: 'rgba(16, 185, 129, 0.08)',
    bgDark: 'rgba(16, 185, 129, 0.15)',
    borderLight: 'rgba(16, 185, 129, 0.25)',
    borderDark: 'rgba(16, 185, 129, 0.3)',
  },
];

export const AI_TOOLS_DATA: AITool[] = [
  // 1. AI CHATBOTS (12 Tools)
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://chatgpt.com',
    iconName: 'Bot',
    accentColor: '#10a37f',
    gradient: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://claude.ai',
    iconName: 'Sparkles',
    accentColor: '#d97706',
    gradient: 'from-amber-600 to-orange-700',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://gemini.google.com',
    iconName: 'Zap',
    accentColor: '#3b82f6',
    gradient: 'from-blue-500 via-indigo-500 to-violet-600',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://perplexity.ai',
    iconName: 'Search',
    accentColor: '#06b6d4',
    gradient: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'grok',
    name: 'Grok',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://grok.com',
    iconName: 'Terminal',
    accentColor: '#ffffff',
    gradient: 'from-slate-700 to-zinc-900',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://chat.deepseek.com',
    iconName: 'Cpu',
    accentColor: '#3b82f6',
    gradient: 'from-blue-600 to-cyan-700',
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://copilot.microsoft.com',
    iconName: 'Layers',
    accentColor: '#0ea5e9',
    gradient: 'from-sky-500 via-indigo-500 to-pink-500',
  },
  {
    id: 'meta-ai-chat',
    name: 'Meta AI',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://meta.ai',
    iconName: 'CircleDot',
    accentColor: '#2563eb',
    gradient: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'mistral',
    name: 'Mistral Le Chat',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://chat.mistral.ai',
    iconName: 'Flame',
    accentColor: '#f97316',
    gradient: 'from-orange-500 to-amber-600',
  },
  {
    id: 'qwen',
    name: 'Qwen',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://qwen.ai',
    iconName: 'Compass',
    accentColor: '#8b5cf6',
    gradient: 'from-purple-600 to-indigo-700',
  },
  {
    id: 'kimi-chat',
    name: 'Kimi',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://kimi.com',
    iconName: 'MessageSquare',
    accentColor: '#3b82f6',
    gradient: 'from-blue-500 to-teal-500',
  },
  {
    id: 'llama',
    name: 'Llama',
    category: 'chatbots',
    categoryLabel: 'AI Chatbot',
    url: 'https://llama.com',
    iconName: 'Activity',
    accentColor: '#6366f1',
    gradient: 'from-indigo-600 to-violet-700',
  },

  // 2. AI VIDEO GENERATION (5 Tools)
  {
    id: 'pixverse',
    name: 'PixVerse',
    category: 'video',
    categoryLabel: 'AI Video',
    url: 'https://pixverse.ai',
    iconName: 'Film',
    accentColor: '#8b5cf6',
    gradient: 'from-purple-600 to-pink-600',
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    category: 'video',
    categoryLabel: 'AI Video',
    url: 'https://klingai.com',
    iconName: 'Clapperboard',
    accentColor: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'google-veo',
    name: 'Google Veo',
    category: 'video',
    categoryLabel: 'AI Video',
    url: 'https://gemini.google.com',
    iconName: 'Video',
    accentColor: '#3b82f6',
    gradient: 'from-blue-500 via-indigo-500 to-purple-600',
  },
  {
    id: 'hailuo-ai',
    name: 'Hailuo AI',
    category: 'video',
    categoryLabel: 'AI Video',
    url: 'https://hailuoai.video',
    iconName: 'PlaySquare',
    accentColor: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    category: 'video',
    categoryLabel: 'AI Video',
    url: 'https://lumalabs.ai',
    iconName: 'Sparkles',
    accentColor: '#10b981',
    gradient: 'from-emerald-500 to-teal-600',
  },

  // 3. AI IMAGE GENERATION (5 Tools)
  {
    id: 'meta-ai-img',
    name: 'Meta AI',
    category: 'image',
    categoryLabel: 'AI Image',
    url: 'https://meta.ai',
    iconName: 'Image',
    accentColor: '#2563eb',
    gradient: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'microsoft-designer',
    name: 'Microsoft Designer',
    category: 'image',
    categoryLabel: 'AI Image',
    url: 'https://designer.microsoft.com',
    iconName: 'Palette',
    accentColor: '#ec4899',
    gradient: 'from-pink-500 via-purple-500 to-indigo-600',
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    category: 'image',
    categoryLabel: 'AI Image',
    url: 'https://ideogram.ai',
    iconName: 'Aperture',
    accentColor: '#f59e0b',
    gradient: 'from-amber-500 to-rose-600',
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo.Ai',
    category: 'image',
    categoryLabel: 'AI Image',
    url: 'https://leonardo.ai',
    iconName: 'Wand2',
    accentColor: '#8b5cf6',
    gradient: 'from-purple-600 to-fuchsia-600',
  },
  {
    id: 'perchance',
    name: 'Perchance',
    category: 'image',
    categoryLabel: 'AI Image',
    url: 'https://perchance.org',
    iconName: 'Dice5',
    accentColor: '#10b981',
    gradient: 'from-emerald-500 to-cyan-600',
  },

  // 4. AI PRESENTATION GENERATION (5 Tools)
  {
    id: 'presenti',
    name: 'Presenti',
    category: 'presentation',
    categoryLabel: 'AI Presentation',
    url: 'https://presenti.ai',
    iconName: 'Presentation',
    accentColor: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 'chatslide',
    name: 'ChatSlide',
    category: 'presentation',
    categoryLabel: 'AI Presentation',
    url: 'https://chatslide.ai',
    iconName: 'Sliders',
    accentColor: '#ec4899',
    gradient: 'from-pink-500 to-rose-600',
  },
  {
    id: 'gamma',
    name: 'Gamma',
    category: 'presentation',
    categoryLabel: 'AI Presentation',
    url: 'https://gamma.app',
    iconName: 'Sparkle',
    accentColor: '#8b5cf6',
    gradient: 'from-violet-600 to-indigo-700',
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'presentation',
    categoryLabel: 'AI Presentation',
    url: 'https://canva.com',
    iconName: 'LayoutTemplate',
    accentColor: '#06b6d4',
    gradient: 'from-cyan-500 to-blue-600',
  },
  {
    id: 'pitch',
    name: 'Pitch',
    category: 'presentation',
    categoryLabel: 'AI Presentation',
    url: 'https://pitch.com',
    iconName: 'MonitorPlay',
    accentColor: '#ec4899',
    gradient: 'from-rose-500 to-pink-600',
  },

  // 5. AI WEBSITE GENERATION (5 Tools)
  {
    id: 'wix',
    name: 'Wix',
    category: 'website',
    categoryLabel: 'AI Website',
    url: 'https://wix.com',
    iconName: 'Globe',
    accentColor: '#10b981',
    gradient: 'from-emerald-500 to-teal-700',
  },
  {
    id: 'framer',
    name: 'Framer',
    category: 'website',
    categoryLabel: 'AI Website',
    url: 'https://framer.com',
    iconName: 'Layout',
    accentColor: '#3b82f6',
    gradient: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'kimi-websites',
    name: 'Kimi Websites',
    category: 'website',
    categoryLabel: 'AI Website',
    url: 'https://kimi.ai',
    iconName: 'PanelTop',
    accentColor: '#06b6d4',
    gradient: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'site123',
    name: 'SITE123',
    category: 'website',
    categoryLabel: 'AI Website',
    url: 'https://site123.com',
    iconName: 'Code',
    accentColor: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 'webador',
    name: 'Webador',
    category: 'website',
    categoryLabel: 'AI Website',
    url: 'https://webador.com',
    iconName: 'AppWindow',
    accentColor: '#8b5cf6',
    gradient: 'from-purple-600 to-indigo-600',
  },
];
